# fly.toml app configuration file generated for airway-web on 2024-09-13T14:21:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'airway-web'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 1999
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
